namespace HousingSociety.Domain
{

    /// <summary>
    /// A residential society/association that contains multiple residents.
    /// </summary>
    public class Society
    {
        /// <summary> Primary key (generated by server). </summary>
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary> Society name (e.g., “Green Meadows”). </summary>
        public string Name { get; set; } = default!;

        /// <summary> Street address / landmark. </summary>
        public string Address { get; set; } = default!;

        /// <summary> City or locality. </summary>
        public string City { get; set; } = default!;

        /// <summary> Optional pincode/postal code. </summary>
        public string? Pincode { get; set; }

        /// <summary> Creation timestamp (UTC). </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }

}
